# Generated by Django 3.1 on 2020-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_theme_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(through='articles.Variant', to='articles.Theme'),
        ),
    ]
