# Generated by Django 3.1 on 2020-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('theme', 'article')},
        ),
    ]
