# Generated by Django 3.1 on 2020-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200825_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(related_name='scope', through='articles.Variant', to='articles.Theme'),
        ),
    ]
